# Database Connection Settings (Remote Hostinger MySQL)
spring.datasource.url=jdbc:mysql://techwing.c122k8qyufqj.ap-south-1.rds.amazonaws.com:3306/autotriage
spring.datasource.username=admin
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate/JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Settings
server.port=8080

# Custom Security Settings
# 256-bit AES Key (Hex Encoded)
security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Token expiration (24 Hours in milliseconds)
security.jwt.expiration-time=86400000