# Database Connection Settings (Remote Hostinger MySQL)
spring.datasource.url=jdbc:mysql://srv1117.hstgr.io:3306/u833088220_satwika?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=u833088220_satwika
spring.datasource.password=Satwika@22823
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate/JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Settings
server.port=8080

# Custom Security Settings
# 256-bit AES Key (Hex Encoded)
security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Token expiration (24 Hours in milliseconds)
security.jwt.expiration-time=86400000
